services:
  nestjs-surrealdb-rest-demo:
    image: koakh/nestjs-surrealdb-rest-demo:1.0.0
    hostname: nestjs-surrealdb-rest-demo
    container_name: nestjs-surrealdb-rest-demo
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nestjs-surrealdb-rest-surrealdb
    ports:
      - 3030:3030
    # environment:
    #   SURREALDB_URL: "ws://127.0.0.1:8000/rpc"
    #   SURREALDB_NAMESPACE: "test"
    #   SURREALDB_DATABASE: "test"
    #   SURREALDB_USERNAME: "root"
    #   SURREALDB_PASSWORD: "root"
    # command: "node dist/main.js"

  nestjs-surrealdb-rest-surrealdb:
    image: surrealdb/surrealdb:v2.3.7
    hostname: surrealdb
    container_name: nestjs-surrealdb-rest-surrealdb
    restart: unless-stopped
    # file:mydb
    command: "start --user root --pass root"
    # uncomment to expose surrealdb port
    ports:
      - 8000:8000
